# Generated by Django 5.2.7 on 2025-10-10 17:41

from django.db import migrations

USERS = [["Dan", "332141ade", True, True], ["lyanez", "lyanez123", False, False]]


def create_default_users(apps, _):
    User = apps.get_model("auth", "User")
    users_data = [
        {
            "username": user[0],
            "password": user[1],
            "is_superuser": user[2],
            "is_staff": user[3],
        }
        for user in USERS
    ]
    for data in users_data:
        if not User.objects.filter(username=data["username"]).exists():
            user = User.objects.create_user(
                username=data["username"], password=data["password"]
            )
            user.is_superuser = data["is_superuser"]
            user.is_staff = data["is_staff"]
            user.save()


def delete_default_users(apps, _):
    User = apps.get_model("auth", "User")
    User.objects.filter(username__in=[user[0] for user in USERS]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("demoproject", "__first__"),
    ]

    operations = [
        migrations.RunPython(create_default_users, delete_default_users),
    ]
